### ISSUE TITLE
As a USER, I want to request to a website, so that I can extract data out of it for further analysis

### ISSUE THREAD

**Issue by tungstennn** [DE-2410-A/web-scraping-syed-abdi#3]

**Comment by tungstennn** [comment]
### Tasks

- [x] Set up venv and install all prerequisites in Jupyter Notebook
- [x] Create and test a function to check successful request
- [x] Create and test function for unsuccessful request
- [x] Create and test function for exception handling

### Functional Requirements
1. The function should accept a url as an input parameter
2. The function should return the status code of the website using requests library
3. The function should handle the response:
       - if the url is valid return '200'
       -
