### ISSUE TITLE
As a USER, I want to be able to extract all the categories and the price points of the books, allowing me to be more informed when launching a rival business

### ISSUE THREAD

**Issue by tungstennn** [DE-2410-A/web-scraping-syed-abdi#4]

**Comment by tungstennn** [comment]
## Tasks

- [ ]  Create and test a function to parse the response
- [ ]  Create and test a function to extract the data
- [ ] Create and test a function to save the data for processing
